"use client";

import {
  CheckCircle2,
  XCircle,
  ShieldCheck,
  AlertTriangle,
  Sparkles,
} from "lucide-react";

interface ResultCardProps {
  analysis: {
    eligible: boolean;
    score: number;
  };
}

export default function ResultCard({
  analysis,
}: ResultCardProps) {
  return (
    <div
      className="
        relative overflow-hidden
        bg-white/80 backdrop-blur-xl
        rounded-[32px]
        border border-white/40
        shadow-[0_20px_60px_rgba(0,0,0,0.08)]
        p-8 md:p-10
      "
    >
      {/* Background Glow */}
      <div
        className={`
          absolute top-0 right-0 w-72 h-72 rounded-full blur-3xl opacity-20
          ${
            analysis.eligible
              ? "bg-emerald-400"
              : "bg-red-400"
          }
        `}
      />

      <div className="relative z-10">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-2 bg-indigo-100 text-indigo-700 px-4 py-2 rounded-full text-sm font-bold mb-5">
              <Sparkles className="w-4 h-4" />
              AI Procurement Analysis
            </div>

            <h2 className="text-3xl md:text-4xl font-black text-slate-900">
              Evaluation Result
            </h2>

            <p className="text-slate-500 mt-3 text-lg">
              Smart eligibility and compliance assessment generated by AI
            </p>
          </div>

          {/* Status Icon */}
          <div
            className={`
              w-28 h-28 rounded-[28px]
              flex items-center justify-center
              shadow-2xl
              ${
                analysis.eligible
                  ? "bg-gradient-to-br from-emerald-500 to-green-600"
                  : "bg-gradient-to-br from-red-500 to-rose-600"
              }
            `}
          >
            {analysis.eligible ? (
              <CheckCircle2 className="w-14 h-14 text-white" />
            ) : (
              <XCircle className="w-14 h-14 text-white" />
            )}
          </div>
        </div>

        {/* Score Section */}
        <div className="mt-12">
          <div className="flex items-end gap-3">
            <span
              className={`
                text-7xl md:text-8xl font-black tracking-tight
                ${
                  analysis.eligible
                    ? "text-emerald-600"
                    : "text-red-600"
                }
              `}
            >
              {analysis.score}
            </span>

            <span className="text-slate-400 text-2xl mb-3 font-bold">
              /100
            </span>
          </div>

          {/* Progress */}
          <div className="mt-8">
            <div className="flex justify-between mb-3">
              <span className="font-bold text-slate-700">
                AI Eligibility Confidence
              </span>

              <span
                className={`font-bold ${
                  analysis.eligible
                    ? "text-emerald-600"
                    : "text-red-600"
                }`}
              >
                {analysis.score}%
              </span>
            </div>

            <div className="w-full h-5 bg-slate-200 rounded-full overflow-hidden">
              <div
                className={`
                  h-full rounded-full transition-all duration-1000
                  ${
                    analysis.eligible
                      ? "bg-gradient-to-r from-emerald-500 to-green-600"
                      : "bg-gradient-to-r from-red-500 to-rose-600"
                  }
                `}
                style={{
                  width: `${analysis.score}%`,
                }}
              />
            </div>
          </div>

          {/* Status */}
          <div className="mt-8 flex flex-wrap gap-4">
            <div
              className={`
                inline-flex items-center gap-2
                px-5 py-3 rounded-2xl
                text-sm font-bold
                shadow-lg
                ${
                  analysis.eligible
                    ? "bg-emerald-100 text-emerald-700"
                    : "bg-red-100 text-red-700"
                }
              `}
            >
              {analysis.eligible ? (
                <ShieldCheck className="w-5 h-5" />
              ) : (
                <AlertTriangle className="w-5 h-5" />
              )}

              {analysis.eligible
                ? "Eligible for Tender Participation"
                : "Compliance Requirements Not Met"}
            </div>

            <div className="inline-flex items-center gap-2 px-5 py-3 rounded-2xl bg-slate-100 text-slate-700 text-sm font-bold">
              AI Verified Analysis
            </div>
          </div>

          {/* Analytics Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mt-10">
            <div className="bg-slate-50 rounded-3xl p-6 border border-slate-100">
              <p className="text-slate-500 text-sm font-medium">
                Procurement Risk
              </p>

              <h3 className="text-3xl font-black text-slate-900 mt-2">
                {analysis.eligible ? "Low" : "High"}
              </h3>
            </div>

            <div className="bg-slate-50 rounded-3xl p-6 border border-slate-100">
              <p className="text-slate-500 text-sm font-medium">
                AI Confidence
              </p>

              <h3 className="text-3xl font-black text-slate-900 mt-2">
                {analysis.score}%
              </h3>
            </div>

            <div className="bg-slate-50 rounded-3xl p-6 border border-slate-100">
              <p className="text-slate-500 text-sm font-medium">
                Evaluation Status
              </p>

              <h3 className="text-3xl font-black text-slate-900 mt-2">
                {analysis.eligible
                  ? "Approved"
                  : "Rejected"}
              </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}